version: '3.4'

services:
  frontend:
    image: frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  backend:
    image: backend
    build:
      context: ./backend
    ports:
      - "4000:4000"